# Generated by Django 2.2b1 on 2019-03-02 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0003_auto_20190302_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_cover_path',
            field=models.CharField(default='', max_length=200),
        ),
    ]
