# Generated by Django 2.2b1 on 2019-03-02 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookshelf", "0005_auto_20190302_0337"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="language",
            field=models.CharField(default="", max_length=200),
        ),
    ]
