# Generated by Django 2.2b1 on 2019-03-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookshelf", "0006_book_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booklist",
            name="date_created",
            field=models.DateField(auto_now_add=True),
        ),
    ]
