# Generated by Django 3.0.1 on 2020-01-19 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookshelf", "0007_auto_20190307_1050"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book", old_name="book_cover_path", new_name="image",
        ),
    ]
