# Generated by Django 3.0.1 on 2020-01-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookshelf", "0008_auto_20200119_0009"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BookList",
        ),
        migrations.AddField(
            model_name="book",
            name="book_id",
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(max_length=200),
        ),
    ]
