# Generated by Django 3.0.1 on 2020-01-19 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookshelf", "0010_auto_20200119_0113"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="edition",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
