# Generated by Django 3.0.1 on 2020-02-01 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookshelf", "0012_bookinfo_publisher"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="publisher_after",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bookshelf.Publisher",
            ),
        ),
    ]
