# Generated by Django 3.0.1 on 2020-02-01 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0014_remove_book_publisher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publisher_after',
            new_name='publisher',
        ),
    ]
