# Generated by Django 3.0.1 on 2020-02-06 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookshelf", "0017_auto_20200201_0747"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookinfo",
            old_name="dateFinishedReading",
            new_name="date_finished_reading",
        ),
    ]
