# Generated by Django 3.0.1 on 2020-02-06 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0018_auto_20200206_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booklist',
            name='book_infos',
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='book_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookshelf.BookList'),
            preserve_default=False,
        ),
    ]
