# Generated by Django 3.0.1 on 2020-02-12 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookshelf", "0020_auto_20200208_0144"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookinfo",
            name="book_list",
        ),
        migrations.AddField(
            model_name="bookinfo",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
