# Generated by Django 3.0.1 on 2020-02-12 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0021_auto_20200212_0116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookList',
        ),
    ]
