# Generated by Django 3.2.6 on 2021-08-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0027_alter_book_edition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.CharField(default='', max_length=80, null=True),
        ),
    ]
