# Generated by Django 3.2.6 on 2021-08-30 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookshelf', '0028_alter_book_edition'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookStatus',
            fields=[
                ('book_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('rating', models.PositiveIntegerField(default=0)),
                ('timestamp', models.PositiveBigIntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='update',
            name='rating',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.DeleteModel(
            name='BookInfo',
        ),
    ]
