# Generated by Django 3.2.6 on 2021-08-30 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0029_auto_20210830_1011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='update',
            options={'ordering': ['timestamp']},
        ),
    ]
