# Generated by Django 3.2.6 on 2021-08-30 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0031_alter_update_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='image',
            new_name='image_url',
        ),
    ]
