# Generated by Django 3.2.6 on 2021-09-06 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0033_rename_type_update_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='book',
        ),
        migrations.AddField(
            model_name='update',
            name='book_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookshelf.bookstatus'),
        ),
    ]
