# Generated by Django 3.2.6 on 2021-09-10 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0034_auto_20210906_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookstatus',
            options={'ordering': ['-timestamp']},
        ),
    ]
