# Generated by Django 3.2.6 on 2021-09-10 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0035_alter_bookstatus_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='image_url',
            new_name='image',
        ),
    ]
